// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh manifest`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/blog/[slug].tsx";
import * as $3 from "./routes/blog/_404.tsx";
import * as $4 from "./routes/gfm.css.ts";
import * as $5 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/blog/[slug].tsx": $2,
    "./routes/blog/_404.tsx": $3,
    "./routes/gfm.css.ts": $4,
    "./routes/index.tsx": $5,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
